title: Hi, I'm Carrie.
description: I'm a student in the Master of Data Science program at UBC, which I will complete in June 2019. This is a compilation of my thoughts on data-related (and not so related) topics by day, and a personal blog of my journey as a data scientist by night.
show_downloads: false
google_analytics:
theme: jekyll-theme-dinky
